name: PythonBootcamp2020
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - ipykernel
  - pip:
    - numpy==1.18.5
    - matplotlib==3.2.2
    - seaborn==0.10.1
    - pandas==1.0.5
    - scipy==1.5.0
    - scikit-learn==0.23.1
