name: PythonBootcamp2024
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=6.1.0
  - bokeh=3.4.1
  - ffmpeg=7.1.0
  - ipympl=0.9.4
  - ipywidgets=8.1.5
  - jupyterlab=4.0.11
  - jupyterlab_widgets=3.0.13
  - jupytext=1.16.4
  - matplotlib=3.8.4
  - nodejs=22.9.0
  - numpy=1.26.4
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - plotly=5.22.0
  - python=3.12.4
  - scikit-image=0.23.2
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - sqlalchemy=2.0.30

