name: PythonBootcamp2022
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=8.0.2
  - jupyterlab=3.4.8
  - jupyterlab_widgets=3.0.3
  - jupytext=1.14.0
  - nodejs=18.10.0
  - numpy=1.20.1
  - pip=22.2.2
  - python=3.9.13
  - pip:
    - astropy==5.1
    - bokeh==2.4.3
    - pandas==1.5.0
    - pillow==9.2.0
    - matplotlib==3.6.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - seaborn==0.11.2

