name: PythonBootcamp2023
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=5.1
  - bokeh=3.2.1
  - ffmpeg=5.1.2
  - ipympl=0.9.3
  - ipywidgets=8.0.4
  - jupyterlab=3.6.3
  - jupyterlab_widgets=3.0.5
  - jupytext=1.14.7
  - matplotlib=3.7.2
  - nodejs=18.16.0
  - numpy=1.24.3
  - pandas=2.0.3
  - pip=23.2.1
  - pillow=9.4.0
  - plotly=5.17.0
  - python=3.11.5
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - sqlalchemy=1.4.39

